name: BedWars1058-PlayAgain
version: '${project.version}'
main: me.cubecrafter.playagain.PlayAgain
api-version: 1.13
author: CubeCrafter
description: Adds the play again feature to BedWars1058!
depend:
  - BedWars1058
permissions:
  bw.playagain.auto:
    description: Permission required to auto queue
    default: op
  bw.playagain.selector:
    description: Permission required to select an arena
    default: true